version: '3.8'

services:
  # --- SSL & Proxy Services ---
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app_network
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=info@applyfollow.com
    networks:
      - app_network
    restart: always

  # --- Application Services ---
  db:
    image: postgres:15
    container_name: applyfollow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REMOVED_FOR_SECURITY
      POSTGRES_DB: applyfollow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: applyfollow_backend
    restart: always
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      # Database Config
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/applyfollow_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: REMOVED_FOR_SECURITY

      # Security
      JWT_SECRET_KEY: REMOVED_FOR_SECURITY
      MAIL_PASSWORD: mail_sifresi_yok

      # CORS - Same Domain oldugu icin aslinda cok esnek olabilir artik
      CORS_ALLOWED_ORIGINS: "*"

      # NGINX CONFIG - ANA DOMAIN ALTINDA /api
      # Frontend ile aynÄ± domaini paylasacak
      VIRTUAL_HOST: applyfollow.com,www.applyfollow.com
      # Bu path ile baslayan istekleri bana (Backend 8080'e) gonder
      VIRTUAL_PATH: /api,/v3/api-docs,/swagger-ui
      LETSENCRYPT_HOST: applyfollow.com,www.applyfollow.com

    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      args:
        # Frontend artik backend'i kendi domaininde bulacak
        NEXT_PUBLIC_API_URL: https://applyfollow.com/api
    container_name: applyfollow_frontend
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      # Browser -> Same Domain /api
      NEXT_PUBLIC_API_URL: https://applyfollow.com/api

      # NGINX CONFIG - ANA DOMAIN (Kalan her sey buraya)
      VIRTUAL_HOST: applyfollow.com,www.applyfollow.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: applyfollow.com,www.applyfollow.com
    networks:
      - app_network

volumes:
  postgres_data:
  certs:
  vhost:
  html:
  acme:


networks:
  app_network:
    driver: bridge
