version: '3.8'

services:
  db:
    image: postgres:15
    container_name: applyfollow_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REMOVED_FOR_SECURITY
      POSTGRES_DB: applyfollow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: applyfollow_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Database Config
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/applyfollow_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: REMOVED_FOR_SECURITY

      # Security & Mail (Bunlari production'da .env dosyasindan almak en iyisidir ama simdilik buraya yaziyoruz)
      JWT_SECRET_KEY: REMOVED_FOR_SECURITY
      MAIL_PASSWORD: mail_sifresi_yok

      # CORS (Frontend Container Name veya IP)
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://5.175.136.4:3000,http://frontend:3000,http://www.applyfollow.com,http://applyfollow.com"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: applyfollow_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # Browser tarafindan erisilecegi icin Public IP olmali (Container ismi degil)
      NEXT_PUBLIC_API_URL: http://5.175.136.4:8080
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
